Skip benches when running on GitHub's build servers
It seems to me that the Windows instances on GitHub's test servers are
not powerful enough to run these:
```
error: test failed, to rerun pass `--lib`
Error: test failed, to rerun pass `--lib`
Caused by:
  process didn't exit successfully: `D:\a\neptune-core\neptune-core\target\debug\deps\neptune_core-0b14cb2984d9a2d2.exe --test-threads=1` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
Error: The process 'C:\Users\runneradmin\.cargo\bin\cargo.exe' failed with exit code 3221226505
```